#!/bin/bash
# GitHub 仓库创建脚本

echo "============================================"
echo "  RuneChronicles GitHub 仓库创建指南"
echo "============================================"
echo ""

echo "📝 方法1：使用 GitHub CLI（推荐，自动化）"
echo ""
echo "# 1. 安装 GitHub CLI（如果未安装）"
echo "brew install gh"
echo ""
echo "# 2. 登录 GitHub"
echo "gh auth login"
echo ""
echo "# 3. 创建仓库并推送"
echo "cd ~/Desktop/RuneChronicles"
echo "gh repo create RuneChronicles --private --source=. --remote=origin --push"
echo ""
echo "# 4. 查看仓库链接"
echo "gh repo view --web"
echo ""

echo "============================================"
echo ""

echo "📝 方法2：手动创建（如果没有 gh CLI）"
echo ""
echo "1. 打开浏览器访问："
echo "   https://github.com/new"
echo ""
echo "2. 填写信息："
echo "   - Repository name: RuneChronicles"
echo "   - Description: 符文编年史 - 卡牌Roguelike游戏"
echo "   - Private/Public: 建议先选 Private"
echo "   - ❌ 不要勾选 'Initialize with README'（我们已有文件）"
echo ""
echo "3. 创建后，GitHub 会显示命令，复制执行："
echo ""
echo "cd ~/Desktop/RuneChronicles"
echo "git remote add origin https://github.com/YOUR_USERNAME/RuneChronicles.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""

echo "============================================"
echo ""

echo "✅ 推送成功后，你的项目就在 GitHub 上了！"
echo ""
echo "🔗 访问你的仓库："
echo "   https://github.com/YOUR_USERNAME/RuneChronicles"
echo ""
